services:
  - type: web
    name: portfolio-website
    env: docker
    plan: free
    repo: https://github.com/jeetendra-kumar-5529/portfolio-website
    branch: main
    dockerfilePath: ./Dockerfile